### ISSUE TITLE
GET content-length header generated incorrectly for signature

### ISSUE THREAD

**Issue by datallah** [inreachventures/aws-signing-request-interceptor#13]
It looks like 32f858ae1e2af10c80552364af453de39d03d71e broke signing GETs.

I now get a 403 response with the following message (slightly sanitized):

> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
> 
> The Canonical String for this request should have been
> 'GET
> /tetris_test/split_records/3A1
> 
> accept-encoding:gzip,deflate
> connection:close
> content-length:
> host:SANITIZED.us-west-2.es.amazonaws.com
> user-agent:Apache-HttpClient/4.5.2 (Java/1.8.0_91)
> x-amz-date:20160510T174638Z
> 
> accept-encoding;connection;content-length;host;user-agent;x-amz-date
> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
> 
> The String-to-Sign should have been
> 'AWS4-HMAC-SHA256
> 20160510T174638Z
> 20160510/us-west-2/es/aws4_request
> a7d878202cc3ba4b24808058eb5f37c1d9b30c8eda9b12201bfc047201d48e23'

When I look at the Canonical String that was actually used for signing, it looks like this (note the "0" for content-length):

> GET
> /tetris_test/split_records/3A1
> 
> accept-encoding:gzip,deflate
> connection:close
> content-length:0
> host:SANITIZED.us-west-2.es.amazonaws.com
> user-agent:Apache-HttpClient/4.5.2 (Java/1.8.0_91)
> x-amz-date:20160510T174638Z
> 
> accept-encoding;connection;content-length;host;user-agent;x-amz-date
> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

**Comment by thesmith** [comment]
You're totally right. Sorry about that.

I've changed the clause to only add a '0' for POSTs, which means GETs and DELETEs get the empty content-length.

I have no idea what the answer is for PUTs, but that *shouldn't* happen.

Please use 0.0.10 and thanks for the contribution.
