### ISSUE TITLE
Adding port to ES URL breaks signature

### ISSUE THREAD

**Issue by semiosis** [inreachventures/aws-signing-request-interceptor#14]
Adding `:80` to the host in the ES server URL breaks signing.  Amazon returns an error showing what they used to compute the signature and the port is missing, so the request fails.

This took me a while to pin down but glad it turned out to be something easy to fix (on my end at least).

Thanks for this helpful interceptor!

**Comment by thesmith** [comment]
The pedantic in me says that this isn't so much a fault of the code but of the usage, as you shouldn't be adding a port to the host header. It would be the same if you added the path, or the scheme. None of them belong there.

In terms of the solution. Wouldn't it be better to validate that the host header is a correctly formatted host, and error with some kind of InvalidArgumentException if it's not? 

I'm thinking Guava's InternetDomainName.from() would be a good validation.

**Comment by semiosis** [comment]
However you want to solve it works for me.  Giving a helpful exception if there's a port number in the ES URL would be nicer than a signature error.

**Comment by semiosis** [comment]
FWIW, port is allowed in the host header, but Amazon removes it before calculating the signature.  Relevant spec: https://tools.ietf.org/html/rfc2616#section-14.23

**Comment by thesmith** [comment]
Oh interesting. In which case I think what you've got there is perfectly reasonable.
Apologies, I assumed that only the host would go in the host header.
