### ISSUE TITLE
Double urlEncode in AWSSigner.java on line 120

### ISSUE THREAD

**Issue by Alexandors** [inreachventures/aws-signing-request-interceptor#26]
Hi,

I'm not sure if it's the correct behavior to urlEncode 2 times for the Uri at line number 120 in AWSSigner.java?

`SdkHttpUtils.urlEncode(SdkHttpUtils.urlEncode(uri, true), true) + RETURN +`

I've downloaded it and fix it to encode only one time to be able to work with AWS Signing 4

Any suggestion?

Cheers,
Arnon K.

**Comment by thesmith** [comment]
Hey, sorry I didn't see the notification for this.

Unfortunately this is an unresolve(d|able) problem. Take a look at #18 and weep.
