### ISSUE TITLE
403 Forbidden while accessing AWS Elastic Search with IAM Role.

### ISSUE THREAD

**Issue by abarnwal13** [inreachventures/aws-signing-request-interceptor#27]
Hi @ericcitaire ,
I was using this library to connect to AWS ES using IAM role. I have added role to my application and then created JestClient using AWS ES endpoint, please refer below code to create JestClient.

`public SElasticSearchClient(final String esEndpoint) {
        this.esEndpoint = esEndpoint;
        final Supplier<LocalDateTime> clock = () -> LocalDateTime.now(ZoneOffset.UTC);
        AWSCredentialsProviderChain awsCredentialsProvider 
                                                                                 = new DefaultAWSCredentialsProviderChain();
        final AWSSigner awsSigner = new AWSSigner(awsCredentialsProvider, "us-east-1", "es", clock);
        final JestClientFactory factory = new JestClientFactory() {
            @Override
            protected HttpClientBuilder configureHttpClient(HttpClientBuilder builder) {
                builder.addInterceptorLast(new AWSSigningRequestInterceptor(awsSigner));
                return builder;
            }
        };
        this.jestClient = initJestClient(factory);
    }`

When I deployed this code and run my application it says error 403 user doesn't have access.
Error Message:
`{
    "Message": "User: arn:aws:sts::*****:assumed-role/search.bulk_ingest/DiscoveryDeAggregator-test is not authorized to perform: es:ESHttpPost on resource: discovery-content2"
}
`
Please let me know what I am missing in code to create JestClient.
Any help will really appreciated
Thanks,
Anish

**Comment by nikhil-sahu** [comment]
@abarnwal13  Did you figure out how to use. Seems access key and id have also to be configured. But i am missing how.

**Comment by thesmith** [comment]
This doesn't seem like an issue with the signer but with your user's permissions. I can't see anything particularly wrong with your code snippet (although formatting it would help).

**Comment by abarnwal13** [comment]
@thesmith : Thanks, the IAM policy was not configured to connect to AWS ES. It is fixed and working fine for core(packages) APIs of JEST client, now I am facing same 403 for for indices(package) API. I build GetAliases request and executed it with jestclient.execute(getAliases). Do I need to configure differently to use indices APIs, can you please let me know ?

**Comment by abarnwal13** [comment]
@nikhil-sahu : Its worked for me, I am able to connect and use core(package) APIs but facing same problem with indices APIs.

**Comment by jebl01** [comment]
**Hijacking this issue with a somewhat relevant note:**

When doing scroll searches, Jest is creating a GET request with the `scroll_id` as a request parameter. This does not work, and my guess is that the `scroll_id` is encoded and signed in a manner that don't suites AWS (ES 2.3). The workaround that worked for me was to not use the SearchScroll builder, but to implement a simple "CustomScrollSearch" and override the default Jest behaviour.

Perhaps this is a valid workaround for more encoding related issues, i.e. see if it's possible to reformat the query and use a POST with a body where Jest creates a GET with query parameters...

The AWS doc also suggests that scroll searches should use a body for `scroll_id` etc

```java
protected Action<? extends JestResult> createSearch() {
    final JsonObject object = new JsonObject();
    object.addProperty(Parameters.SCROLL, "3m");
    object.addProperty(Parameters.SCROLL_ID, scrollId);

    return new CustomScrollSearch(new Search.Builder(object.toString()));
}

public class CustomScrollSearch extends Search {
    protected CustomScrollSearch(final Builder builder) {
        super(builder);
    }

    @Override
    protected String buildURI() {
        return "_search/scroll";
    }
}
```

**Comment by thesmith** [comment]
So I am able to use the index API just fine, but generally with write requests. Maybe the is issue is with particular kinds of GET requests and the way characters are encoded.

As usual, I'll need more information. Let me know what version of the library you're using and what the actual error message is (beyond just 403). We need to look at what parameters were signed and what amazon expected the signature to be.

What's odd is that I would expect you to be getting a 401, not a 403. 403 indicates that the request was correct, but your user is forbidden from doing whatever it wants to do.

**Comment by nikhil-sahu** [comment]
I am facing the same issue.
When I try to programatically create a index via jest, it gives me a error:

`{"message":"The security token included in the request is invalid."}`

config is :

    @Bean
    public JestClient jestClient() {

    DefaultAWSCredentialsProviderChain awsCredentialsProvider = new DefaultAWSCredentialsProviderChain();

        final AWSSigner awsSigner = new AWSSigner(awsCredentialsProvider, REGION, SERVICE, () -> LocalDateTime.now(ZoneOffset.UTC));

        final AWSSigningRequestInterceptor requestInterceptor = new AWSSigningRequestInterceptor(awsSigner);

        final JestClientFactory factory = new JestClientFactory() {

            @Override
            protected HttpClientBuilder configureHttpClient(HttpClientBuilder builder) {
                builder.addInterceptorLast(requestInterceptor);
                return builder;
            }

            @Override
            protected HttpAsyncClientBuilder configureHttpClient(HttpAsyncClientBuilder builder) {
                builder.addInterceptorLast(requestInterceptor);
                return builder;
            }
        };


        factory.setHttpClientConfig(new HttpClientConfig.Builder(esURIs)
                .multiThreaded(true)
                .connTimeout(connTimeout)
                .readTimeout(readTimeout)
                .maxTotalConnection(50)
                .discoveryEnabled(false)
                .build());

        return factory.getObject();
    }

**Comment by thesmith** [comment]
Could you try testing with the BasicAWSCredentials? I just want to check that it's failing with the specific credentials you think you are using.

`new StaticCredentialsProvider(new BasicAWSCredentials(awsKey, awsSecret))`

**Comment by thesmith** [comment]
Out of interest, what's the name of the index you're creating?

**Comment by nikhil-sahu** [comment]
Worked with StaticCredentialsProvider. Strange that same keys did not work with DefaultChain . Names were `users` and `tests` .

**Comment by thesmith** [comment]
I did a bit of Googling and found some received the same error when they had different credentials on their chain that took precedent.

**Comment by nikhil-sahu** [comment]
Ok. Found the issue.

Seems I was expecting DefaultChain to read from SystemPropertiesCredentialsProvider and it was internally using 

`System.getProperty("aws.accessKeyId")`

to read the property. However I am providing the properties in the `application.properties` file (since using spring ) and these properties are not accessible via native `System.getProperty`calls. So credentials would have been null/empty . Although AWS should have thrown 401 and not 403 in such a case.

**Comment by nikhil-sahu** [comment]
However , how could names of the index be playing any role in that? Would things change if I were to include a special character(most probably `_` or `-`) in the name of the index ?

**Comment by thesmith** [comment]
I have no idea. The default chain seems to cause a few people problems. Glad you got it working though
