### ISSUE TITLE
signing fails with asterisks in query param value

### ISSUE THREAD

**Issue by homes2001** [inreachventures/aws-signing-request-interceptor#31]
When a query parameter value contains an asterisks, the request signing fails and AWS returns an error:

> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The reason is that AWS expects more characters in the URL to be encoded than what is necessary at the minimum. The Java SDK URLEncoder does not encode the asterisks. Here is the corresponding code from the AWS SDK: https://github.com/aws/aws-sdk-java/blob/7e064a48bee151ef222e0edea6157c1e65c7904a/aws-java-sdk-core/src/main/java/com/amazonaws/util/SdkHttpUtils.java#L66

**Comment by thesmith** [comment]
Thank you. It works in my tests.

**Comment by homes2001** [comment]
great, thanks for the quick merge and maven release :+1:
