### ISSUE TITLE
Does you library support streaming?

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [inreachventures/aws-signing-request-interceptor#33]
I have created  [repository](https://github.com/C-h-e-r-r-y/aws-signing-request-interceptor-bug) with bug reproducing.

> This repo contains a maven project with 2 java classes NonWorkingExampleStreamVersion, WorkingExampleNonStreamVersion. Both of them has main method. Both take file from s3 and try to store it in aws elasticsearch. But:

> WorkingExampleNonStreamVersion - load whole file content into byte stream, creates base64 from it and then send file to elasticsearch
NonWorkingExampleStreamVersion - do the same thins as previous but instead of downloading whole file it wrap stream and uploads bytes to elaticsearch only when those byte arrives from s3. This version is does not work due to:
> ````
>      "message": "The request signature we calculated does not match the signature you provided. Check > your AWS Secret Access Key and signing method. Consult the service documentation for details.
> ````

More details you can see on reaadme.md file. Feel free to ask me any questions.

**Comment by thesmith** [comment]
I'm assuming it doesn't. I think the library needs to be able to set the right content length header, so buffers everything. 

Guessing it would need to be converted to support this: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

I would be surprised if I get to do this any time soon. PRs are always welcome :)

**Comment by micw** [comment]
Seems that the library itself buffers nothing. If I use InputStreamEntity for request which is not repeatable, it fails. If I use ByteArrayEntity, it works.
Streaming of responses is works.
