### ISSUE TITLE
signing fails with spaces encoded as plus in query string

### ISSUE THREAD

**Issue by homes2001** [inreachventures/aws-signing-request-interceptor#34]
When a URL like `http://host/path?a=b+c` is signed, the signature is wrong.

**Comment by thesmith** [comment]
Care to elaborate?

**Comment by homes2001** [comment]
Just uploaded a fix including a test case. I have found this bug when working with Elastic Search and sending queries that include spaces in the query string. Elastic search encodes the space with a `+` sign, which results in invalid signatures being calculated.
