### ISSUE TITLE
Error try to connect ElasticSearch  aws 6.2 with jest client

### ISSUE THREAD

**Issue by apolo92** [inreachventures/aws-signing-request-interceptor#37]
Hi

I worked this library in elasticsearch versions 2.3 and 5.5 and run corretly. But I try to pass ElasticSearch 6.2 and when I executed http petition get mapping (GET schneider/user/_mapping).

I recived next error: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details"

Is possible change security parameters in this version ES ? because in previous versions run correlty,
Thanks

**Comment by marnix** [comment]
We've experienced this as well.

As far as we can see, this is independent of the version of ElasticSearch, this is _new_ (or updated/reconfigured?) ES domains vs _older_ / existing ones.

It looks like new ES domains (which use new AMIs with OS etc. bugfixes) correctly implement [the AWS4 algorithm](https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html), and older ES domains didn't.  That is why this library has a workaround for a specific scenario, see https://github.com/inreachventures/aws-signing-request-interceptor/blob/763f261a9916d48d0f2efb5dc69b97d9a737003b/src/main/java/vc/inreach/aws/request/AWSSigner.java#L163-L167.

With this workaround, this library is sending wrong signatures (i.e., different from the docs) in these scenarios, to get them accepted by older ES domains.  However, the newer ES domains now expect correct signatures, resulting in the error you report.

(The scenario is when you do an HTTP GET, or any non-POST, with a `Content-Length: 0` header.  Older ES domains incorrectly treated this request as if you'd sent `Content-Length:`, so an empty header value.)

A better workaround, IMHO, is: _don't use the `Content-Length` header in signing / `SignedHeaders`_.  That makes this library work with both older and newer AWS domain.

**Comment by XiaoConstantine** [comment]
@marnix How can I not use `Content-length` head in signing? Could you be more specific?

**Comment by marnix** [comment]
If the above is unclear, I've created (as yet untested) pull request #38.

**Comment by apolo92** [comment]
NICEEE!!! your pull request work it!. 

Yes after write issue. I continue to investigate and view two differences when responses run ok.
content-length = 0 and miss content-Type headers. But i dont have idea that problem is a new AMIs.

Thanks marnix!

When this pull request publishing to new version?

**Comment by thesmith** [comment]
We need to put this change through some tests. When I get some time I'll run my tests on it, although I'm largely targeting older versions of ES. If it looks good I'll merge and release.

**Comment by thesmith** [comment]
Ok, I've merged and released this. You should find 0.0.21 in mvn central in the next few hours.
