### ISSUE TITLE
Refresh index failed

### ISSUE THREAD

**Issue by zplinti1** [inreachventures/aws-signing-request-interceptor#8]
There is not error when query and insert data to AWS Elasticsearch service. But When I refresh an index like:
`      Refresh refresh = new Refresh.Builder().addIndex(index).build();
        JestResult jestResult = _jestClient.execute(refresh);`
And get an error return.
CONTEXT=index=newlmes_idx_28_1456704000000, jsonResult={"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/newlmes_idx_28_1456704000000/_refresh\na=b\naccept-encoding:gzip,deflate\nconnection:close\ncontent-length:0\ncontent-type:application/json; charset=UTF-8\nhost:search-xxx.ap-northeast-1.es.amazonaws.com\nuser-agent:Apache-HttpClient/4.4.1 (Java/1.7.0_71)\nx-amz-date:20160405T091625Z\n\naccept-encoding;connection;content-length;content-type;host;user-agent;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20160405T091625Z\n20160405/ap-northeast-1/es/aws4_request\n87dc94bf640ae0c2e61071265eda687ee8c6dae9968b460687f836df717e798d'\n"}

**Comment by thesmith** [comment]
You'll need to print out the stringToSign variable and see what is different to what AWS are returning to you there in the error.

**Comment by thesmith** [comment]
If the strings-to-sign are identical and the signature is different, maybe take a look at http://docs.aws.amazon.com/general/latest/gr/signature-v4-test-suite.html and see if you can work out where my code is getting it wrong.

**Comment by thesmith** [comment]
Bump?

**Comment by thesmith** [comment]
Ok, I worked out what was going on. This is now fixed in 0.0.9.
