### ISSUE TITLE
scan and scroll query failed

### ISSUE THREAD

**Issue by zplinti1** [inreachventures/aws-signing-request-interceptor#9]
When I write a scroll query like this:
`SearchScroll searchScroll = new SearchScroll.Builder(_scrollId, _scrollExpirationTime).build();`

AWSSigningRequestInterceptor throw an exception:
`Caused by: java.lang.IllegalArgumentException: Chunk [scroll_id=c2NhbjsxOzc3Mjo5WGljUUFNeVJGcVdDSzBjaUVQcDJ3OzE7dG90YWxfaGl0czo1NTg0Ow==] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:512)
	at com.logicmonitor.lmes.elasticsearch.aws.AWSSigningRequestInterceptor.params(AWSSigningRequestInterceptor.java:)`

I use JestClient 0.1.6

**Comment by thesmith** [comment]
Ah shit, I bet I know what that is. I'll take a look at fixing it asap.

**Comment by thesmith** [comment]
Ok, thanks for reporting. This should be fixed now - it was a dumb bug that couldn't deal with a = in the param values.

This has been released as 0.0.7
